spring:
  application:
    name: UserProject
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://localhost:3306/api_knot
    username: root
    password: Slayer.khamra04/killer
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

  redis:
    host: localhost
    port: 6379

  cache:
    type: redis

  zipkin:
    base-url: http://localhost:9411
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
sentry:
  dsn: https://dccf839f99b7f1c330edbc15d78ece41@o4509219345530880.ingest.de.sentry.io/4509219347038289
  send-default-pii: true
  exception-resolver-order: -2147483647

