services:
  amqp:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: LuisPiquinRey
      RABBITMQ_DEFAULT_PASS: "Slayer.khamra04/killer"
    ports:
      - "5672:5672"
      - "15672:15672"
