
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: amqp
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: LuisPiquinRey
      RABBITMQ_DEFAULT_PASS: "Slayer.khamra04/killer"
  redis:
    image: redis:7.2
    container_name: redis-cache
    ports:
      - "6379:6379"
    restart: always