
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: amqp
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: LuisPiquinRey
      RABBITMQ_DEFAULT_PASS: "Slayer.khamra04/killer"


