services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: amqp
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: LuisPiquinRey
      RABBITMQ_DEFAULT_PASS: Slayer.khamra04killer
      RABBITMQ_DEFAULT_VHOST: /
    restart: always

  redis:
    image: redis:7.2
    container_name: redis-cachecat
    ports:
      - "6379:6379"
    restart: always

  nexus:
    image: sonatype/nexus3
    container_name: nexusContainer
    ports:
      - "9090:8081"
    restart: always

  db-primary:
    image: mysql:8.0
    container_name: mysqlPrimary
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Slayer.khamra04/killer
      MYSQL_DATABASE: knotcommerce
    volumes:
      - ./initSql:/docker-entrypoint-initdb.d
    restart: always

  db-secondary:
    image: mysql:8.0
    container_name: mysqlSecondary
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Slayer.khamra04/killer
      MYSQL_DATABASE: knotcommerce
    volumes:
      - ./initSql:/docker-entrypoint-initdb.d
    restart: always
