spring:
    application:
        name: KnotCommerce
    rabbitmq:
        listener:
            simple:
                retry:
                    enabled: true
                    max-attempts: 3
                    initial-interval: 1000
        host: localhost
        port: 5672
        username: LuisPiquinRey
        password: Slayer.khamra04killer
        virtual-host: /
    neo4j:
        uri: neo4j+s://597fd0f7.databases.neo4j.io
        authentication:
            password: g5NQX9qcDn2MLj9QrrxYmwDcaNPEDxeX7TV-esvfHgI
            username: neo4j
    cloud:
        config:
            enabled: true
    liquibase:
        change-log: classpath:db/changelog/db.changelog-master.xml
    output:
        ansi:
            enabled: ALWAYS
    messages:
        basename: ValidationMessages
    batch:
        jdbc:
            initialize-schema: always
            isolation-level-for-create: DEFAULT
        job:
            enabled: true
    config:
        import: configserver:http://localhost:8071/
    jpa:
        hibernate:
            ddl-auto: none
    data:
        redis:
            host: localhost
            port:  6379
    cache:
            type: redis
server:
    port: 8080
    servlet:
        context-path: /api
    shutdown: immediate
logging:
    level:
        "[org.springframework.amqp]": DEBUG
        "[org.springframework.amqp.rabbit.core.RabbitAdmin]": DEBUG
    charset:
        console: UTF-8
    pattern:
        console: "
%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){red}  \
%clr(%-5level){yellow}  \
%clr(${PID}){green}  \
%clr(---){cyan}  \
%clr([%thread]){blue}  \
%clr(%-40.40logger{0}){magenta}  \
%clr(:){faint}  \
%clr(%msg){white}%n%wex"