spring:
    application:
        name: KnotCommerce
    datasource:
        url: jdbc:mysql://localhost:3306/knotcommerce
        username: root
        password: ENC(ktL34tS1spH/eiMOqJ+uzXWWtqRjOLobyviv1BFNi836KZPQAIqPnA==)
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
    output:
        ansi:
            enabled: ALWAYS
server:
    port: 8080
    servlet:
        context-path: /api
    shutdown: immediate
logging:
    charset:
        console: UTF-8
    pattern:
        console: "
%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){red}  \
%clr(%-5level){yellow}  \
%clr(${PID}){green}  \
%clr(---){cyan}  \
%clr([%thread]){blue}  \
%clr(%-40.40logger{0}){magenta}  \
%clr(:){faint}  \
%clr(%msg){white}%n%wex"
jasypt:
    encryptor:
        password: LuisPiquinRey
        algorithm: PBEWithMD5AndDES