spring:
    application:
        name: KnotCommerce
    config:
        import: configserver:http://localhost:8071/
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
            enabled: true