spring:
    application:
        name: stripe-service
    rabbitmq:
        listener:
            simple:
                retry:
                    enabled: true
                    max-attempts: 3
                    initial-interval: 3000
        host: localhost
        port: 5672
        username: LuisPiquinRey
        password: Slayer.khamra04killer
logging:
    level:
        "[org.springframework.amqp]": DEBUG
        "[org.springframework.amqp.rabbit.core.RabbitAdmin]": DEBUG
server:
    port: 8060
    servlet:
        context-path: /stripe