spring:
    application:
        name: centralizedServerMicroservices
    profiles:
        active: git
    output:
        ansi:
            enabled: ALWAYS
    cloud:
        config:
            server:
                git:
                    uri: "https://github.com/LuisPiquinRey/centralizedServerMicroservices.git"
                    username: LuisPiquinRey
                    password: ${GIT_PASSWORD}
                    default-label: main
                    timeout:  5
                    clone-on-start: true
                    force-pull: true
eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: "http://localhost:8761/eureka/"
logging:
    charset:
        console: UTF-8
    pattern:
        console: "\
%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){bright_yellow}  \
%clr(%-5level){green}  \
%clr(${PID}){green}  \
%clr(---){green}  \
%clr([%thread]){green}  \
%clr(%-40.40logger{0}){green}  \
%clr(:){green}  \
%clr(%msg){white}%n%wex"

server:
    port: 8071