<<<<<<< HEAD
spring:
    app:
        jwtSecret: s3cR3tK3y!9x7*Bv@fL1#QzYpRw2T^UcMnXg
    application:
        name: MicroservicesUsers
    config:
        import: configserver:http://localhost:8071/
    output:
        ansi:
            enabled: always
    liquibase:
        change-log: classpath:db/changelog/db.changelog-master.xml
        clear-checksums: false

    security:
        user:
            name: LuisPiquinRey
            password: LuisPiquinRey
server:
    port: 8090
logging:
    level:
        org:
            springframework:
                security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}
management:
    endpoints:
        web:
            exposure:
=======
spring:
    app:
        jwtSecret: s3cR3tK3y!9x7*Bv@fL1#QzYpRw2T^UcMnXg
    application:
        name: MicroservicesUsers
    config:
        import: configserver:http://localhost:8071/
    output:
        ansi:
            enabled: always
    liquibase:
        change-log: classpath:db/changelog/db.changelog-master.xml
        clear-checksums: false

    security:
        user:
            name: LuisPiquinRey
            password: LuisPiquinRey
server:
    port: 8090
logging:
    level:
        org:
            springframework:
                security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}
management:
    endpoints:
        web:
            exposure:
>>>>>>> e137109867be5cf7b442a0dfe4a113623fd5ca9f
                include: refresh