spring:
    application:
        name: MicroservicesUsers
    config:
        import: configserver:http://localhost:8071/
    app:
        jwtSecret: "czNjUjN0SzN5ITl4NypCdkBmTDEjUXpZcFJ3MlRdVWNNblhn"
        privateKeySSL: ${PRIVATE_KEY_OPENSSL}
