name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Check Java version
        run: java -version

      - name: Run tests with Maven
        run: mvn test
        working-directory: ./KnotCommerce

      - name: Show test results
        run: cat target/surefire-reports/*.txt
        working-directory: ./KnotCommerce

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Build with Maven
        run: mvn clean install
        working-directory: ./KnotCommerce

      - name: Show content
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          ls -la
        working-directory: ./KnotCommerce

      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: /target/*.jar
