name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v3.14.1
        with:
          java-version: '21'
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Check Java version
        run: java -version
      - name: Run tests with Maven
        run: mvn test
      - name: Show test results
        run: |
          echo "Test results:"
          cat target/surefire-reports/*.txt
        continue-on-error: true  # Esto sigue ejecutándose incluso si el test falla, para ver los resultados.

  build:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        runs-on: [ubuntu-latest, windows-latest]
    needs: test
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v3.14.1
        with:
          java-version: '21'
      - name: Build with Maven
        run: mvn clean install
      - name: Show content
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          ls -la
          echo "Running action: ${{ github.action }}"
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4.6.2
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'
